### ISSUE TITLE
conbench CLI: logging error in runner record() method

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1055]
In #621 we replaced `print()`s with logging. There was a mistake in this line:
https://github.com/conbench/conbench/blob/61fac4e5c12ee4b71a493929662e580084e4186b/conbench/util.py#L173
Whenever the `Conbench.record()` method is called, this results in the following LoggingError. (The code still continues past the line.)
<details>
 <summary>Traceback</summary>

```
--- Logging error ---
Traceback (most recent call last):
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/bin/conbench", line 8, in <module>
    sys.exit(conbench())
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/conbench/cli.py", line 149, in _benchmark
    for result, output in benchmark().run(**kwargs):
  File "my_benchmark.py", line 427, in run
    yield self.conbench.record(**record_kwargs)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/conbench/runner.py", line 322, in record
    self.publish(benchmark_result)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/conbench/util.py", line 154, in publish
    self.post(self.config.benchmarks_url, benchmark)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/conbench/util.py", line 163, in post
    self._post(self.config.login_url, self.config.credentials, 204)
  File "/tmp/conda-01875206-650b-44b0-b980-841363c0ac72/lib/python3.10/site-packages/conbench/util.py", line 173, in _post
    log.info("Time to POST", url, time.monotonic() - start)
Message: 'Time to POST'
Arguments: ('<url>/api/login/', 0.402172212023288)
```
</details>

**Comment by jgehrcke** [comment]
:) what's not tested is broken. Yes. :) 

This was probably the intention:
```
log.info("Time to POST to %s: %.4f s", ...
```

**Comment by jgehrcke** [comment]
Adding `devprod` label because of the challenge in the test-coverage-maintenance space. We maintain this, but it's not properly covered by tests. Improving that state would mean to do less/no maintenance, or more tests.

**Comment by jgehrcke** [comment]
One question is: why did linting tooling not catch this?
