### ISSUE TITLE
instability: ci / db-migrations: `psycopg2.OperationalError) could not connect to server: Connection refused`

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1117]
```
Run make alembic-new-migration
docker compose down --remove-orphans
 Container conbench-app-run-1316bbd3[9](https://github.com/conbench/conbench/actions/runs/4698131258/jobs/8330049321?pr=1116#step:5:10)14c  Stopping
 Container conbench-app-run-1316bbd3914c  Stopping
 Container conbench-app-run-1316bbd3914c  Stopped
 Container conbench-app-run-1316bbd3914c  Removing
 Container conbench-app-run-[13](https://github.com/conbench/conbench/actions/runs/4698131258/jobs/8330049321?pr=1116#step:5:14)16bbd3914c  Removed

...

[230414-09:00:29.170] [1] [conbench.db] INFO: create sqlalchemy DB engine
[230414-09:00:29.173] [1] [conbench.db] INFO: bind engine to session
[230414-09:00:29.225] [1] [conbench] DEBUG: re-configure logging
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 636, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "db" (172.19.0.4) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
make: *** [Makefile:100: alembic-new-migration] Error 1
Error: Process completed with exit code 2.
```

it's in the Alembic DB connect routine:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/usr/local/lib/python3.11/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.11/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrations/env.py", line 101, in <module>
    run_migrations_online()
  File "/app/migrations/env.py", line 89, in run_migrations_online
    with connectable.connect() as connection:
         ^^^^^^^^^^^^^^^^^^^^^
```
probably no retrying.

**Comment by jgehrcke** [comment]
Seems to be rather rare. Closing for now. Let's reopen when this starts to hurt. Let's however always track occurrences as we see them.
