### ISSUE TITLE
benchmark result view: hist plot render: sigfig: `ValueError: invalid input Character "n" (position 1, state A)`

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1155]
Seen for staging/benchmark-results/064458556d0a7178800039f9ef44f47f/
```
File "/app/conbench/app/results.py", line 239, in page
plotinfo = self.get_history_plot(benchmark, run)
File "/app/conbench/app/_plots.py", line 64, in get_history_plot
time_series_plot(samples, benchmark, run),
File "/app/conbench/app/_plots.py", line 476, in time_series_plot
formatted, axis_unit = _should_format([s.mean for s in samples], unit)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/conbench/app/_plots.py", line 188, in _should_format
units_formatted.add(unit_fmt(f, unit).split(" ", 1)[1])
^^^^^^^^^^^^^^^^
File "/app/conbench/units.py", line 53, in fmt_unit
return f"{sigfig.round(value, sigfigs=4)} {unit}"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 579, in round
given = _arguments_parse(args, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 274, in _arguments_parse
given['num'] = _num_parse(args[0])
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 547, in _num_parse
A(num)
File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 480, in A
raise ValueError('invalid input Character "%s" (position %d, state A)' % (num[0], i))
ValueError: invalid input Character "n" (position 1, state A)
```

**Comment by jgehrcke** [comment]
Relevant benchmark result stats:
```
  "stats": {
    "data": [
      402.365759388078
    ],
    "iqr": null,
    "iterations": 1,
    "max": null,
    "mean": null,
    "median": null,
    "min": null,
    "q1": null,
    "q3": null,
    "stdev": null,
    "time_unit": "s",
    "times": [],
    "unit": "s",
    "z_improvement": false,
    "z_regression": false,
    "z_score": null
  },
```
That is, `mean` is not set, and sigfig tries to work with `null`/None, that might somehow lead to `invalid input Character "n"`. But in Python code this should translate to `None` and not the literal string `"null"`. Hm ohoh.
Related: https://github.com/conbench/conbench/pull/1127

**Comment by jgehrcke** [comment]
After https://github.com/conbench/conbench/pull/1160 this still crashes.

> That is, mean is not set, and sigfig tries to work with null/None, that might somehow lead to invalid input Character "n". But in Python code this should translate to None and not the literal string "null". 

Let's add clarity into this. I did deeper inspection after realizing that my focus on api/benchmark-results/064458556d0a7178800039f9ef44f47f/ was maybe too limited. Rendering the benchmark result view in the UI triggers evaluating history, so the bad sample might not come from the main result at hand, but from its history. 

So, I looked at /api/history/064458556d0a7178800039f9ef44f47f/ and then did pretty-print via https://jsonformatter.org/json-pretty-print, which reasonably answered
```
Parse error on line 1:
...c145dc215da","mean":NaN,"repository":"ht
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

Tracking this JSON compliance topic in https://github.com/conbench/conbench/issues/1163.

I then had a hunch and reproduced the exception from the log excerpt above locally:
```
$ python
Python 3.11.1 (main, Jan 23 2023, 14:59:28) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sigfig
>>> sigfig.round(
KeyboardInterrupt
>>> import math
>>> sigfig.round(math.nan, sigfigs=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jp/.pyenv/versions/3111-conbench3/lib/python3.11/site-packages/sigfig/sigfig.py", line 579, in round
    given = _arguments_parse(args, kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3111-conbench3/lib/python3.11/site-packages/sigfig/sigfig.py", line 274, in _arguments_parse
    given['num'] = _num_parse(args[0])
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3111-conbench3/lib/python3.11/site-packages/sigfig/sigfig.py", line 547, in _num_parse
    A(num)
  File "/home/jp/.pyenv/versions/3111-conbench3/lib/python3.11/site-packages/sigfig/sigfig.py", line 480, in A
    raise ValueError('invalid input Character "%s" (position %d, state A)' % (num[0], i))
ValueError: invalid input Character "n" (position 1, state A)
```

**Comment by jgehrcke** [comment]
That last patch in https://github.com/conbench/conbench/pull/1164 has maybe worsened the situation, judging by a report from @deepsihag.

See https://github.com/conbench/conbench/pull/1164/files#r1175633354.

**Comment by jgehrcke** [comment]
This was fixed by https://github.com/conbench/conbench/pull/1172.
