### ISSUE TITLE
gunicorn worker shutdown: periodically_set_q_rem does not shut down upon SIGTERM

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1161]
When developing with `make run-app-dev` I noticed that the periodically_set_q_rem thread might delay gunicorn worker process shutdown unnecessarily long, sometimes triggering the  `WORKER TIMEOUT` condition:
```
conbench-app-1  | [230424-10:37:27.379] [4553] [conbench.job] INFO: BMRT cache job (started: True): saw signal 15, set shutdown flag
conbench-app-1  | 
conbench-app-1  | worker_int hook: send myself SIGTERM
conbench-app-1  | [2023-04-24 10:37:27 +0000] [4553] [INFO] Worker exiting (pid: 4553)
conbench-app-1  | [2023-04-24 10:39:27 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:4553)
conbench-app-1  | Exception ignored in: <module 'threading' from '/usr/local/lib/python3.11/threading.py'>
conbench-app-1  | Traceback (most recent call last):
conbench-app-1  |   File "/usr/local/lib/python3.11/threading.py", line 1583, in _shutdown
conbench-app-1  |     lock.acquire()
conbench-app-1  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
conbench-app-1  |     sys.exit(1)
conbench-app-1  | SystemExit: 1
conbench-app-1  | [2023-04-24 10:39:27 +0000] [4701] [INFO] Booting worker with pid: 4701
```
See, SIGTERM was sent to self.

But then two minutes passed:
```
conbench-app-1  | [2023-04-24 10:37:27 +0000] [4553] [INFO] Worker exiting (pid: 4553)
conbench-app-1  | [2023-04-24 10:39:27 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:4553)
```

This is a no-go for local dev (the quick app reload upon file saving is an important feature).

**Comment by jgehrcke** [comment]
Done in https://github.com/conbench/conbench/pull/1162.
