### ISSUE TITLE
benchadapt: "scrape commit info from local repo" feature, used by Arrow CI, was removed by #1135

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1232]
We removed a feature that we assumed has no consumers. Assumption was wrong. See https://github.com/conbench/conbench/pull/1135#issuecomment-1537110851.

Fallout was amplified by dependency between arrow repo and conbench repo being defined as moving target.

This is about "scraping commit info from file system", see
https://github.com/apache/arrow/blob/b43f4cd4ce28e2ddb7bad89081e141f381b09d5e/ci/scripts/go_bench_adapt.py#L42

```
else:
    github = None  # scrape github info from the local repo
    run_reason = "branch"
```

Fallout:
```
230505-17:58:56.410 WARNING: command `['sysctl', '-n', 'hw.memsize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/memsize: No such file or directory
Traceback (most recent call last):
  File "/home/runner/work/arrow/arrow/ci/scripts/go_bench_adapt.py", line 102, in <module>
    go_adapter()
  File "/home/runner/.local/lib/python3.10/site-packages/benchadapt/adapters/_adapter.py", line 79, in __call__
    self.run(**kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/benchadapt/adapters/_adapter.py", line 100, in run
    self.results = self.transform_results()
  File "/home/runner/.local/lib/python3.10/site-packages/benchadapt/adapters/_adapter.py", line 111, in transform_results
    results = self._transform_results()
  File "/home/runner/work/arrow/arrow/ci/scripts/go_bench_adapt.py", line 94, in _transform_results
    parsed.run_name = f"{parsed.run_reason}: {parsed.github['commit']}"
TypeError: 'NoneType' object is not subscriptable
```
(https://github.com/apache/arrow/actions/runs/4859969743/jobs/8742255231).
Thanks for reporting @zeroshade

Fundamental problem (that's an opinion, but based on quite a bit of painful exprience like this one here): we should not have a moving target here:
https://github.com/apache/arrow/blob/b43f4cd4ce28e2ddb7bad89081e141f381b09d5e/.github/workflows/go.yml#L122
https://github.com/apache/arrow/blob/b43f4cd4ce28e2ddb7bad89081e141f381b09d5e/.github/workflows/go.yml#L293

**Comment by jgehrcke** [comment]
While in fact arrow CI used that feature, it did not do so intentionally. See https://github.com/apache/arrow/pull/35467.
Closing this here.
