### ISSUE TITLE
API compare/runs/id...id: `KeyError: 'contender_z_regression'`

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1280]
@jonkeane noticed that an arrow CI step failed with `KeyError: 'contender_z_regression'`
```
[2023-05-22 15:31:44,591] INFO in __init__: send: GET https://conbench.ursa.dev/api/compare/runs/17b4a87d9e8b4e18b1c5ae6ecf830631...ab127cf7c191483d9ba89fda37fc3950/
[2023-05-22 15:31:44,786] INFO in __init__: reply: 200
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/buildkite/schedule_and_publish/publish_benchmark_results_on_pull_requests.py", line 21, in publish_benchmark_results_on_pull_requests
    new_comment_body = notification.generate_pull_comment_body()
  File "/app/models/notification.py", line 89, in generate_pull_comment_body
    + self.generate_comment_with_compare_runs_links()
  File "/app/models/notification.py", line 62, in generate_comment_with_compare_runs_links
    status = self.benchmarkable.machine_runs_status(machine)
  File "/app/models/benchmarkable.py", line 204, in machine_runs_status
    raise e
  File "/app/models/benchmarkable.py", line 185, in machine_runs_status
    regressions, improvements = self.regressions_and_improvements(machine)
  File "/app/models/benchmarkable.py", line 252, in regressions_and_improvements
    len([r for r in results if r["contender_z_regression"]])
  File "/app/models/benchmarkable.py", line 252, in <listcomp>
    len([r for r in results if r["contender_z_regression"]])
KeyError: 'contender_z_regression'
```

todo:
- identify the responsible change
- identity the severity for arrow CI (looks bad currently, but do we at least record the results, or does that crash before that?)
- think about solutions (change API again to heal this, or change consumer?)

**Comment by alistaire47** [comment]
At a glance that looks like it's due to the change to the `/api/compare` schema, which was one of the changes that just got deployed to that instance. If that's correct, we'll need a PR to arrow-benchmarks-ci to update the keys

**Comment by jonkeane** [comment]
Would you mind taking a look at doing that @alistaire47 ?

**Comment by alistaire47** [comment]
PR up (linked above). Not sure if a bk test build would test it? But it's a pretty simple change.

**Comment by alistaire47** [comment]
Closing this as resolved since it looks like https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/114 worked; can reopen if it's being masked by other issues and reappears
