### ISSUE TITLE
benchmark result page: (transient?) internal server error for a certain benchmark result

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1321]
I went to this page: https://conbench.ursa.dev/benchmark-results/0648a542ccb77b4c8000cf84b87e0f97/

and got this
```
unexpected exception, please report this:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/_endpoint.py", line 28, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/results.py", line 281, in get
    return self.page(
           ^^^^^^^^^^
  File "/app/conbench/app/results.py", line 243, in page
    plotinfo = self.get_history_plot(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/_plots.py", line 125, in get_history_plot
    time_series_plot(
  File "/app/conbench/app/_plots.py", line 589, in time_series_plot
    source_rolling_alert_min_over_time = _source(
                                         ^^^^^^^^
  File "/app/conbench/app/_plots.py", line 366, in _source
    strings.append(", ".join(unit_fmt(ss, unit) for ss in subsamples))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/_plots.py", line 366, in <genexpr>
    strings.append(", ".join(unit_fmt(ss, unit) for ss in subsamples))
                             ^^^^^^^^^^^^^^^^^^
  File "/app/conbench/units.py", line 57, in fmt_unit
    return f"{sigfig.round(value, sigfigs=4)} {unit}"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 579, in round
    given = _arguments_parse(args, kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 274, in _arguments_parse
    given['num'] = _num_parse(args[0])
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 547, in _num_parse
    A(num)
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 478, in A
    B(num[1:])
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 491, in B
    number.increment_power_by(n)
  File "/usr/local/lib/python3.11/site-packages/sigfig/sigfig.py", line 104, in increment_power_by
    tmp[key + n] = self.map[key]
                   ~~~~~~~~^^^^^
KeyError: -5
```
But now when I refresh, the page renders properly. We didn't make any deployments so the data must have changed. Monitor this.

**Comment by jgehrcke** [comment]
Interesting. Thanks for putting the full traceback here. Hope we can reproduce/understand.

**Comment by jgehrcke** [comment]
Let's maybe close this until we see this again. As of today, `conbench/units.py` does not even import sigfig anymore.
