### ISSUE TITLE
ci instability: ui-screenshots fails with chromedriver download

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1364]
Fails right now:

```
Files removed: 49
Removing intermediate container 59044a88c08a
 ---> 6c810b825cd8
Step 5/6 : RUN python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
 ---> Running in efa7ebc483e3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/drivers/chrome.py", line 40, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/core/driver.py", line 51, in get_driver_version_to_download
    self._driver_to_download_version = self._version if self._version not in (None, "latest") else self.get_latest_release_version()
                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/drivers/chrome.py", line 62, in get_latest_release_version
    resp = self._http_client.get(url=latest_release_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 37, in get
    self.validate_response(resp)
  File "/usr/local/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
The command '/bin/sh -c python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"' returned a non-zero code: 1

Error: Process completed with exit code 1.
```

Let's see, this might resolve itself. `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790` is indeed not available right now, but maybe that's just a hiccup in some rollout somewhere. 

If this keeps failing for longer than say a day then let's look into changing code on our side.

**Comment by jgehrcke** [comment]
A build against `main` was just found to be broken as of this, too. Let's consider this permanent for now, and prioritize fixing it.

**Comment by jgehrcke** [comment]
reproduced locally:
```
#0 0.857 ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
------
screenshot.Dockerfile:19
--------------------
```

**Comment by jgehrcke** [comment]
cause and fallout discussed here: https://github.com/SergeyPirogov/webdriver_manager/issues/536

**Comment by jgehrcke** [comment]
Resolved for now.
