### ISSUE TITLE
`conbench --help` tries to load all benchmarks

### ISSUE THREAD

**Issue by pitrou** [conbench/conbench#1387]
It seems that simply asking for help tries to import all benchmarks which 1) makes the CLI much less responsive 2) fails when some benchmark dependency is missing (for example PyArrow hasn't been compiled yet).
```console
$ conbench --help
/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (None)/charset_normalizer (3.2.0) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/antoine/mambaforge/envs/pyarrow/bin/conbench", line 5, in <module>
    from conbench.cli import conbench
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/conbench/cli.py", line 9, in <module>
    register_benchmarks()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/conbench/util.py", line 311, in register_benchmarks
    import_path(f"{directory}/{filename}", root=entry)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/pathlib.py", line 565, in import_path
    importlib.import_module(module_name)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/antoine/arrow/benchmarks/benchmarks/partitioned_dataset_filter_benchmark.py", line 3, in <module>
    from benchmarks import _benchmark
  File "/home/antoine/arrow/benchmarks/benchmarks/_benchmark.py", line 13, in <module>
    import pyarrow
  File "/home/antoine/arrow/dev/python/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: XXX
```

**Comment by alistaire47** [comment]
`conbench --help` lists all benchmarks in the current directory because it turns them into commands:

https://github.com/conbench/conbench/blob/abe388b06967643cc42cb98ff9f8c4b67a0b7c66/conbench/cli.py#L84-L171

so

``` shell
$ conbench --help
[230726-12:10:11.295] [95488] [benchadapt.adapters] INFO: Initializing adapter
Usage: conbench [OPTIONS] COMMAND [ARGS]...

  Conbench: Language-independent Continuous Benchmarking (CB) Framework

Options:
  --help  Show this message and exit.

Commands:
  cpp-micro                   Run the Arrow C++ micro benchmarks.
  csv-read                    Run csv-read benchmark(s).
  csv-write                   Run csv-write benchmark(s).
  dataframe-to-table          Run dataframe-to-table benchmark.
  dataset-filter              Run dataset-filter benchmark.
  dataset-read                Run dataset-read benchmark(s).
  dataset-select              Run dataset-select benchmark.
  dataset-selectivity         Run dataset-selectivity benchmark(s).
  dataset-serialize           Run dataset-serialize benchmark(s).
  example-R-only              Run example-R-only benchmark.
  example-R-only-exception    Run example-R-only-exception benchmark(s).
  example-R-only-nonexistent  Run example-R-only-nonexistent benchmark.
  example-cases               Run example-cases benchmark(s).
  example-cases-exception     Run example-cases-exception benchmark(s).
  example-external            Run example-external benchmark.
  example-simple              Run example-simple benchmark.
  example-simple-exception    Run example-simple-exception benchmark.
  file-read                   Run file-read benchmark(s).
  file-write                  Run file-write benchmark(s).
  java-micro                  Run the Arrow Java micro benchmarks.
  js-micro                    Run the Arrow JavaScript micro benchmarks.
  list                        List of benchmarks (for orchestration).
  partitioned-dataset-filter  Run partitioned-dataset-filter benchmark(s).
  recursive-get-file-info     Run recursive-get-file-info benchmark(s).
  tpch                        Run tpch benchmark(s).
  version                     Display Conbench version.
  wide-dataframe              Run wide-dataframe benchmark(s).
```

 so I'm not sure this is fixable without restructuring how the CLI is structured, unfortunately

**Comment by jgehrcke** [comment]
Thank you @pitrou! Yes, this is an architecture smell and a pretty massive error handling weakness.

We should have clearly stated on Slack that this `conbench` CLI is not an area where we invest energy. It suffers from a number of architectural and implementation weaknesses. In the team we treat it as legacy/deprecated. It still exists because it's deeply entangled in CI, and it takes quite a bit of energy to remove/replace it. But yeah, that kind of energy is better invested (so, we should keep pushing for replacement).

Sorry that this isn't clearly documented. Closing the ticket for now.
