### ISSUE TITLE
ci breakage: `ci-screenshot` fails with This version of ChromeDriver only supports Chrome version 115

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1472]
```
230913-13:17:31.583 root INFO: provided URL to open in browser: http://127.0.0.1:32770
230913-13:17:31.583 root INFO: set up chromedriver with capabilities {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'goog:chromeOptions': {'extensions': [], 'args': ['--headless', '--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage']}}
Traceback (most recent call last):
  File "//screenshot.py", line 269, in <module>
    main()
  File "//screenshot.py", line 97, in main
    screenshot(url_to_open, png_path)
  File "//screenshot.py", line 110, in screenshot
    with _get_driver() as driver:
         ^^^^^^^^^^^^^
  File "//screenshot.py", line 249, in _get_driver
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 117.0.5938.62 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x55a66c009783 <unknown>
```

we probably want to back out of the workaround I recently did in https://github.com/conbench/conbench/pull/1367, the dust has certainly settled by now

**Comment by jgehrcke** [comment]
Taken care of via https://github.com/conbench/conbench/pull/1473.
