### ISSUE TITLE
Getting "Invalid email or password." when trying to use `post_results()`

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1519]
Could someone please tell me how to set up or get the password in order to use `.post_results()` on a local conbench server? 
I get this error
```
231028-11:05:17.499 INFO: Initializing conbench client
231028-11:05:17.569 ERROR: Failed request: POST http://127.0.0.1:5000/api/login/ {"email": "deamarialeon@gmail.com", "password": "innocent-registration-key"}
231028-11:05:17.569 ERROR: Response content: {"code": 400, "description": {"_errors": ["Invalid email or password."]}, "name": "Bad Request"}
Traceback (most recent call last):
  File "/Users/dealeon/conbench/client.py", line 22, in <module>
    adapter.post_results()
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchadapt/adapters/_adapter.py", line 165, in post_results
    client = ConbenchClient()
             ^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchclients/conbench.py", line 42, in __init__
    self.post("/login/", json=login_creds)
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchclients/base.py", line 64, in post
    self._maybe_raise(req_string=req_string, res=res)
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchclients/base.py", line 85, in _maybe_raise
    res.raise_for_status()
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://127.0.0.1:5000/api/login/
```
I have a local server running (after using `make run-app-dev`). 

Do I need a .conbench "credential file"? or do I need to run the server not in a container like I'm doing?

**Comment by DeaMariaLeon** [comment]
Never mind, sorry for the noise.
