### ISSUE TITLE
BUG:  breaks when clicking on a case id - after searching for a benchmark by name

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1537]
When there are not enough data for a graph, searching for a benchmark by name and then
clicking on a case id, I see this:
```
unexpected exception, please report this:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/_endpoint.py", line 28, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/conbench/app/benchmarks.py", line 669, in show_benchmark_results
    y_unit_for_all_plots = maybe_longer_unit(units_seen.pop())
                                             ^^^^^^^^^^^^^^^^
KeyError: 'pop from an empty set'
```

**Comment by austin3dickey** [comment]
Thanks for the bug report! Looks like in your setup this branch was taken every time:
https://github.com/conbench/conbench/blob/b3cb3c369c19a9b4fff1d92186f0b2216fa6dc72/conbench/app/benchmarks.py#L609-L610

We probably should expect this and return an informative message in that case. 🙂

**Comment by DeaMariaLeon** [comment]
Actually, it was not the same branch every time. The problem was that I was including the date to the context. So the date was creating a different context for every result in the benchmark. And every time I had just "one result".

**Comment by austin3dickey** [comment]
Ah yes, we've struggled in the past with the correct balance of attributes that break history every time and ones that don't.
