### ISSUE TITLE
TypeError when using AlertPipeline

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1556]
Trying to use benchalert with a minimum local setup (and the gitHub app for that repo, etc):

```
commit_hash = "9ca24902dd16e53d8586df9f828c27d24138478a"
repo = "git@github.com:DeaMariaLeon/algos2"
pipeline = AlertPipeline(
    steps=[
        steps.GetConbenchZComparisonStep(
            commit_hash=commit_hash,
            baseline_run_type=steps.BaselineRunCandidates.parent,
        ),
        steps.GitHubCheckStep(
            commit_hash=commit_hash,
            comparison_step_name="GetConbenchZComparisonStep",
            github_client=GitHubRepoClient(repo=repo),
        ),
    ],
)
print(pipeline.run_pipeline())
```

There is this error:

```
231220-14:48:35.202 INFO: try: GET to http://127.0.0.1:5000/api/compare/runs/d03c23cb4c99446aa6eca5201aa4e3e0...a155693c28854b63877535b20281c877/
231220-14:48:35.229 INFO: GET request to http://127.0.0.1:5000/api/compare/runs/d03c23cb4c99446aa6eca5201aa4e3e0...a155693c28854b63877535b20281c877/: took 0.0273 s, response status code: 200
[{'analysis': {'lookback_z_score': {'improvement_indicated': False, 'regression_indicated': False, 'z_score': -2.256, 'z_threshold': 5.0}, 'pairwise': {'improvement_indicated': False, 'percent_change': -30.78, 'percent_threshold': 5.0, 'regression_indicated': True}}, 'baseline': {'batch_id': '4637f8173c784ae59b9350d257523f90', 'benchmark_name': 'benchmarks.TimeSuite.time_insertion_sort', 'benchmark_result_id': '06582b0da08a783e80007404df0bbbfa', 'case_permutation': 'no-permutations', 'error': None, 'language': 'Python', 'run_id': 'd03c23cb4c99446aa6eca5201aa4e3e0', 'single_value_summary': 1.303, 'tags': {'name': 'benchmarks.TimeSuite.time_insertion_sort'}}, 'contender': {'batch_id': 'e9f8f937b4204ced8bc0a47be7f23992', 'benchmark_name': 'benchmarks.TimeSuite.time_insertion_sort', 'benchmark_result_id': '06582b0dc49a7f8d80006716ac558b40', 'case_permutation': 'no-permutations', 'error': None, 'language': 'Python', 'run_id': 'a155693c28854b63877535b20281c877', 'single_value_summary': 1.704, 'tags': {'name': 'benchmarks.TimeSuite.time_insertion_sort'}}, 'less_is_better': True, 'unit': 's'}]
Traceback (most recent call last):
  File "/Users/dealeon/conbench_toy/alert.py", line 48, in <module>
    print(pipeline.run_pipeline())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchalerts/alert_pipeline.py", line 88, in run_pipeline
    step_outputs[step.step_name] = step.run_step(
                                   ^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchalerts/pipeline_steps/conbench.py", line 201, in run_step
    return super().run_step(previous_outputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchalerts/pipeline_steps/conbench.py", line 86, in run_step
    run_comparison = self._get_one_run_comparison(run_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchalerts/pipeline_steps/conbench.py", line 117, in _get_one_run_comparison
    run_comparison.compare_results = self.conbench_client.get_all(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench/lib/python3.12/site-packages/benchclients/conbench.py", line 190, in get_all
    data = resp_json["data"]
           ~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

When I tried to see what was going on in [conbench.py](https://github.com/conbench/conbench/blob/main/benchclients/python/benchclients/conbench.py) ,  the `type` of `resp_json` is list. But if I try to print(resp_json[0]), it shows it like a dictionary and there is a key error 0! 

Any ideas would be appreciated.
Thanks.

**Comment by austin3dickey** [comment]
Hey, thanks for the issue. This looks to be a versioning mismatch. I believe that `benchalerts==2023.12.18` will only work with Conbench servers that are using this commit or later: https://github.com/conbench/conbench/commit/ad06af92ec215c5e0fbd848a89493abc45fd8e0d

(We changed the schema of certain endpoints so that clients can paginate. But it looks like your Conbench server is returning the old schema.)

I'm not sure how your Conbench server is set up, but can you check that it's using the latest commit from the `main` branch?

**Comment by DeaMariaLeon** [comment]
Thanks a lot. The server set up is the "local containerized fashion". So I use `make run-app`. 
I cleaned up the images and I think that part is OK now... it went up to my next error. 😅
