### ISSUE TITLE
Alert system question

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1557]
Do I have to create a check-run on the repo that I'm benchmarking, and then conbench alert system will add to it? (I thought it created it).
But for the error that I get, I might be missing the check-run. Could you please confirm? (since it's another new subject, I want to make sure that's the issue). Thanks in advance.

This is the error:

```
231221-17:28:09.058 INFO: GET request to http://127.0.0.1:5000/api/compare/runs/8714bb356fda43129548d4b8c40f56e0...9a88294fbcea4e38b5b887bedfdb490e/: took 0.0283 s, response status code: 200
231221-17:28:09.265 ERROR: Failed request: POST https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs {"name": "Conbench performance report", "head_sha": "c8a9c2fd3bcf23a21acfa6f4cffbc4c9360b9ea6", "conclusion": "failure", "completed_at": "2023-12-21T16:28:09.059218Z", "output": {"title": "Found 1 regression", "summary": "Conbench analyzed the 1 benchmark run on commit `c8a9c2fd`.\n\n## Benchmarks with performance regressions\n\nThere was 1 possible performance regression, according to the lookback z-score method.\n\n### Benchmarks with regressions:\n\n- Commit Run on `Deas-MacBook-Air.local` at [2023-12-21 14:15:32Z](http://127.0.0.1:5000/compare/runs/8714bb356fda43129548d4b8c40f56e0...9a88294fbcea4e38b5b887bedfdb490e/)\n  - [`benchmarks.TimeSuite.time_insertion_sort` (Python)](http://127.0.0.1:5000/compare/benchmarks/0658309ccfc5731d8000400b3c5c132b...065844887dba78a78000ff3ef2d44311)\n\n## All benchmark runs analyzed:\n\n- Commit Run on `Deas-MacBook-Air.local` at [2023-12-21 14:15:32Z](http://127.0.0.1:5000/runs/9a88294fbcea4e38b5b887bedfdb490e)", "text": "This report was generated using the lookback z-score method with a z-score threshold of -1.0."}, "details_url": "http://127.0.0.1:5000"}
231221-17:28:09.266 ERROR: Response content: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/checks/runs#create-a-check-run"}
231221-17:28:09.481 ERROR: Failed request: POST https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs {"name": "Conbench performance report", "head_sha": "c8a9c2fd3bcf23a21acfa6f4cffbc4c9360b9ea6", "conclusion": "neutral", "completed_at": "2023-12-21T16:28:09.270273Z", "output": {"title": "Error when analyzing performance", "summary": "The CI build running the regression analysis failed. This does not necessarily mean this commit has benchmark regressions, but there is an error that must be resolved before we can find out.", "text": "Error: `HTTPError('404 Client Error: Not Found for url: https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs')`\n\nSee build link below."}, "details_url": "https://github.com/git@github.com:DeaMariaLeon/algos2/actions/runs/7289196759"}
231221-17:28:09.481 ERROR: Response content: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/checks/runs#create-a-check-run"}
Traceback (most recent call last):
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/alert_pipeline.py", line 88, in run_pipeline
    step_outputs[step.step_name] = step.run_step(
                                   ^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/pipeline_steps/github.py", line 99, in run_step
    res = self.github_client.update_check(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/integrations/github.py", line 271, in update_check
    return self.post("/check-runs", json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchclients/base.py", line 64, in post
    self._maybe_raise(req_string=req_string, res=res)
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchclients/base.py", line 85, in _maybe_raise
    res.raise_for_status()
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dealeon/conbench_toy/alert.py", line 51, in <module>
    print(pipeline.run_pipeline())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/alert_pipeline.py", line 94, in run_pipeline
    error_handler.handle_error(exc=exc, traceback=format_exc())
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/pipeline_steps/github.py", line 237, in handle_error
    res = self.github_client.update_check(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchalerts/integrations/github.py", line 271, in update_check
    return self.post("/check-runs", json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchclients/base.py", line 64, in post
    self._maybe_raise(req_string=req_string, res=res)
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/benchclients/base.py", line 85, in _maybe_raise
    res.raise_for_status()
  File "/Users/dealeon/mambaforge/envs/conbench2/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs
```

**Comment by austin3dickey** [comment]
When I've received the 404 Not Found error from the GitHub API in the past, it's usually because the credentials I provided don't have access to that repo. Did you follow [these instructions](https://github.com/conbench/conbench/tree/main/benchalerts#creating-a-github-app-to-work-with-benchalerts) to set up an App?

**Comment by DeaMariaLeon** [comment]
Yes, I did follow those instructions to set up the App.
Edit:
But you were right of course. The error was `GITHUB_REPOSITORY`. I thought it was the same as `REPOSITORY`.

~~It's trying to post the report here:~~

~~https://api.github.com/repos/git@github.com:DeaMariaLeon/algos2/check-runs~~

~~But that subdirectory doesn't exist. That's why I was asking about the check-runs. OK, I'll continue tomorrow. Thank you.~~
