### ISSUE TITLE
staging deployment failure

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1561]
Buildkite logs:
```
trap 'kill -- $$' INT TERM QUIT; source .buildkite/utils.sh run_migrations
++ aws eks --region us-east-2 update-kubeconfig --name vd-2
Updated context ... in /var/lib/buildkite-agent/.kube/config
++ kubectl config set-context --current --namespace=staging
Context "..." modified.
++ sed 's|{{CONBENCH_WEBAPP_IMAGE_SPEC}}|...|g'
++ kubectl delete --ignore-not-found=true -f _jobspec
configmap "conbench-migration-config" deleted
job.batch "conbench-migration" deleted
++ kubectl apply -f _jobspec
configmap/conbench-migration-config created
job.batch/conbench-migration created
++ kubectl wait --for=condition=complete --timeout=86400s job/conbench-migration
error: timed out waiting for the condition on jobs/conbench-migration
🚨 Error: The command exited with status 1
```
Pod logs:
```
[240102-17:40:56.052] [7] [conbench.db] INFO: psycopg2.__libpq_version__: 160001
[240102-17:40:56.247] [7] [conbench.entities.commit] INFO: GITHUB_API_TOKEN env is set, length of data: 40
[240102-17:40:56.247] [7] [conbench.entities.commit] INFO: configured a single GitHub HTTP API auth token
[240102-17:40:56.521] [7] [conbench.buildinfo] INFO: decoded build info JSON: {'branch_name': 'main', 'version_string': 'cc83fc6ef-dev', 'commit': 'cc83fc6ef184867023ee77357f95ba5546ce5bcb', 'build_time_rfc3339': '2024-01-02 17:36:55Z', 'build_hostname': 'ip-10-1-6-75.us-east-2.compute.internal'}
[240102-17:40:56.874] [7] [conbench.db] INFO: create sqlalchemy DB engine
[240102-17:40:56.876] [7] [conbench.db] INFO: bind engine to session
[240102-17:40:56.922] [7] [conbench] DEBUG: re-configure logging
[240102-17:40:56.922] [7] [conbench] INFO: Flask app config object:
{...}
Conbench config object:
{...}
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 608, in run_cmd
    fn(
  File "/usr/local/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrations/env.py", line 30, in <module>
    config.set_main_option("sqlalchemy.url", sqlalchemy_url)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 272, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 299, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/local/lib/python3.11/configparser.py", line 1220, in set
    super().set(section, option, value)
  File "/usr/local/lib/python3.11/configparser.py", line 910, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql://...' at position 22
```
I redacted the database connection string but suspect there's a moving target dependency problem that's causing the database password to start failing on this code.

**Comment by austin3dickey** [comment]
Tried a rebuild just in case; same symptom.

**Comment by austin3dickey** [comment]
There is a `*` in the database password that's now being URL-encoded to `%2A` somewhere before it gets here:

https://github.com/conbench/conbench/blob/cc83fc6ef184867023ee77357f95ba5546ce5bcb/migrations/env.py#L30

And alembic can't handle single percent signs in config values since that's a special symbol for interpolation. That's what caused this particular error. Now we need to figure out why the password is suddenly being URL-encoded and how to stop it.

**Comment by austin3dickey** [comment]
Yep, moving targets!
<img width="925" alt="image" src="https://github.com/conbench/conbench/assets/16600275/0c004c78-d17e-499c-86fd-bc84e988446e">
