### ISSUE TITLE
Question about error message

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1604]
Hello,
Are you familiar with this error? 
If so, could you share your ideas?
Thanks

```
240824-18:46:11.992 INFO: Initializing adapter
240824-18:46:11.992 INFO: Running benchmarks with command: `echo ./asv_files/asv_files/2522b0ab-env-c196b4341bbba99577f508fef14fa55a.json`
./asv_files/asv_files/2522b0ab-env-c196b4341bbba99577f508fef14fa55a.json
240824-18:46:11.996 INFO: Benchmark run completed
240824-18:46:11.996 INFO: Transforming results for conbench
240824-18:46:12.412 INFO: Results transformation completed
240824-18:46:12.412 INFO: Initializing conbench client
240824-18:46:12.412 INFO: try to perform login
240824-18:46:12.412 INFO: try: POST to http://0.0.0.0:5000/api/login/
240824-18:46:12.627 INFO: POST request to http://0.0.0.0:5000/api/login/: took 0.2149 s, response status code: 204
240824-18:46:12.628 INFO: ConbenchClient: initialized
240824-18:46:12.628 INFO: Posting results to conbench
240824-18:46:12.628 INFO: try: POST to http://0.0.0.0:5000/api/benchmarks/
240824-18:46:12.688 INFO: POST request to http://0.0.0.0:5000/api/benchmarks/: took 0.0594 s, response status code: 500
240824-18:46:12.688 INFO: unexpected response. code: 500 (retryable), body bytes: <unexpected exception, please report this:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidSchemaName: sch ...>
```

**Comment by austin3dickey** [comment]
Hey @DeaMariaLeon , it looks like the full error message is cut off due to this line:
https://github.com/conbench/conbench/blob/da7fb4c2b4874a33789243a60887a8b432359c7f/benchclients/python/benchclients/http.py#L373

So that makes this a little tricky to debug. Would you be able to either edit your local copy of `benchclients` or make a manual POST to your Conbench instance to see if you can find the full error message?

In the meantime, to directly answer your question, no I haven't seen this error before. The `InvalidSchemaName` implies to me that maybe something is wrong with the configuration of your database. It would be interesting to see what DB schema the code is trying to access, and why that schema doesn't exist.

**Comment by DeaMariaLeon** [comment]
Thanks a lot for your reply. I'll check that.

**Comment by DeaMariaLeon** [comment]
The problem was caused by the latest `numpy` version. 
Closing this now.
