### ISSUE TITLE
ci: db-populate: RemoteDisconnected upon first benchmark POST

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#555]
https://github.com/conbench/conbench/issues/531#issuecomment-1360906252

I have also just now seen this in CI for the first time:
```
Traceback (most recent call last):
  File "/home/runner/work/conbench/conbench/conbench/tests/populate_local_conbench.py", line 361, in <module>
    create_benchmarks_data()
  File "/home/runner/work/conbench/conbench/conbench/tests/populate_local_conbench.py", line 290, in create_benchmarks_data
    post_benchmarks(benchmark_data)
  File "/home/runner/work/conbench/conbench/conbench/tests/populate_local_conbench.py", line 207, in post_benchmarks
    res = session.post(url, json=data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
make: *** [Makefile:27: db-populate] Error 1
Error: Process completed with exit code 2.
```

**Comment by jgehrcke** [comment]
Good new is that I invalidated the user agent hypothesis: https://github.com/conbench/conbench/actions/runs/3749556432/jobs/6368167039#step:6:97

A retry helps:
```
221221-13:20:34.198 INFO: POST to url: http://127.0.0.1:49154/api/benchmarks/
221221-13:21:04.965 INFO: attempt 0 failed with ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) after 30.76740
221221-13:21:04.965 INFO: POST to url: http://127.0.0.1:49154/api/benchmarks/ 
```
So, that's a transient issue that reproduces. The first attempt I think triggers machinery that triggers the problem.

**Comment by jgehrcke** [comment]
Emitting container logs after failure. Shows:
```
conbench-app-1 | 127.0.0.1 - - [21/Dec/2022:13:25:10 +0000] "GET /api/ping/ HTTP/1.1" 200 110 "-" "curl/7.74.0"
conbench-app-1 | [2022-12-21 13:25:13 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:12)
conbench-app-1 | Finding all commits to the master branch of apache/arrow between 1970-01-01T00:00:00Z and 2022-03-03T14:16:51Z
conbench-app-1 | [2022-12-21 13:25:13 +0000] [12] [INFO] Worker exiting (pid: 12)
```

That is, a 30 s worker timeout was responsible around commit fetching -- this problem is tracked here: https://github.com/conbench/conbench/issues/543

**Comment by jgehrcke** [comment]
I have addressed this with retrying as part of https://github.com/conbench/conbench/pull/553.

This does not solve the root cause, but I think reliably works around that for now. Root cause I think has to do with GitHub HTTP API interaction taking more time than worker timeout. Tracking that specific challenge here: https://github.com/conbench/conbench/issues/556

**Comment by jgehrcke** [comment]
Closing this as 'resolved'.
