### ISSUE TITLE
POST BenchmarkResult: missing `name` key results in HTTP response with code 500

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#935]
I saw https://github.com/conbench/conbench/blob/5154d8bdf540dc4d6600df4712e94bd27b9d6f6c/conbench/entities/benchmark_result.py#L194

and tested
```
>>> {1:2}.pop("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'foo'
```

and then confirmed that 

```
conbench-app-1  | 172.22.0.1 - - [22/Mar/2023:13:54:59 +0000] "POST /api/benchmarks/ HTTP/1.1" 500 0 "-" "-" (0.002664 s)
conbench-app-1  | [2023-03-22 13:54:59 +0000] [8] [ERROR] Error handling request /api/benchmarks/
...
conbench-app-1  |   File "/app/conbench/entities/benchmark_result.py", line 194, in create
conbench-app-1  |     name = tags.pop("name")
conbench-app-1  |            ^^^^^^^^^^^^^^^^
conbench-app-1  | KeyError: 'name'
```

action items:
- document this in api spec
- emit 400 bad request resp with proper err msg
- cover with tests

**Comment by jgehrcke** [comment]
> document this in api spec

Did that here: https://github.com/conbench/conbench/commit/9237373f99b2aa04906496e0393eabc0ec1ecd45

"The special key "name" must be provided with a string value: it indicates the name of the conceptual benchmark that was performed for obtaining the result at hand"

> emit 400 bad request resp with proper err msg

https://github.com/conbench/conbench/pull/1126

> cover with tests

still a TODO

**Comment by jgehrcke** [comment]
> cover with tests

Oh, I did that here:

https://github.com/conbench/conbench/commit/fdaa36d263cb28ccf5697c286a5b11aa1b633512

So, we can close this issue as 'done'.
